import type { Metadata } from "next";
import "../globals.css";
import MainSidebar from "@/components/Layout-Components/MainSidebar";
import SearchComponent from "@/components/Search";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <div className="flex">
      <MainSidebar/>
        <main className="flex-grow">
          {children}
        </main>
      </div>
  );
}
